quimera_robot:
          
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  right_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_right_wheel_joint
  left_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_left_wheel_joint

  # mobile_base_controller:
  #   type: diff_drive_controller/DiffDriveController
  #   publish_rate: 50

  #   left_wheel: 'back_left_wheel_joint'
  #   right_wheel: 'back_right_wheel_joint'


